<?php

require_once('inc/telepresence.api.inc');
require_once('inc/telepresence.admin.inc');

function telepresence_permission() {
	$perms = array();
	$perms['access telepresence'] = array(
		'title' => 'Access Telepresence Portal',
		'description' => 'Allows user to view video feeds on the telepresence page.');
	$perms['administer telepresence'] = array(
		'title' => 'Administer Telepresence Portal Configuration',
		'description' => 'Change settings and content related to the telepresence module.');
	return $perms;
}

function telepresence_menu() {
	$items = array();
	$items['telepresence'] = array(
		'page callback' => 'telepresence_page',
		'access arguments' => array('access telepresence'),
		'type' => MENU_NORMAL_ITEM
	);
	$items['admin/config/telepresence'] = array(
		'title' => 'Telepresence Configuration',
		'description' => t('Configuration options for the Telepresence application'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('telepresence_config'),
		'access arguments' => array('administer telepresence'),
		'type' => MENU_NORMAL_ITEM
	);
	$items['admin/manage-telepresence-cameras'] = array(
		'title' => 'Manage Telepresence Cameras',
		'page callback' => 'telepresence_add_camera',
		'access arguments' => array('administer telepresence'),
		'type' => MENU_NORMAL_ITEM
		);

	$items['admin/telepresence/bookmark'] = array(
		'page callback' => 'bookmark_action',
		// Change this back to administer when done debugging!!!!!!!
		'access arguments' => array('access telepresence'),
		'type' => MENU_CALLBACK);

	$items['telepresence/api/cameras'] = array(
		'page callback' => 'telepresence_api',
		'access arguments' => array('access telepresence'),
		'type' => MENU_CALLBACK
		);
	return $items;
}

function telepresence_page() {
	$about       = telepresence_get_settings();
	$module_path = drupal_get_path('module', 'telepresence');
	$flex_api    = variable_get('telepresence_api', '');
	$module_api  = '/telepresence/api';

	drupal_add_css($module_path . '/public/css/font-awesome/css/font-awesome.min.css');
	drupal_add_css($module_path . '/public/css/kendo.common.min.css');
	drupal_add_css($module_path . '/public/css/kendo.metro.min.css');

	drupal_add_css($module_path . '/public/bower_components/Bani/dist/bani-views.min.css');

	drupal_add_js(
		array(
			'modulePath'         => $module_path,
			'telepresence_about' => $about,
			'flex_api'           => $flex_api,
			'module_api'         => $module_api
		),
		'setting'
	);

	drupal_add_css($module_path . '/public/css/telepresence.css');

	// Both of the following add additional layering and can be used interchangably (you can switch themes using the Telepresence.switchTheme method in the javasctpt console)
	/**
	 * OPTIONS
	 * @@@@@@@
	 * theme-light
	 * theme-extra-light
	 */

	drupal_add_css($module_path . '/public/css/telepresence-light.css');
	drupal_add_css($module_path . '/public/css/telepresence-extra-light.css');

	drupal_add_css($module_path . '/public/bower_components/backbone.toggleSwitch/main.css');

	if(user_access('administer telepresence')) {
		drupal_add_css($module_path . '/public/css/admin.css');
	}

	$page = theme('telepresence_template', array('module_path' => $module_path));
	
	return $page;
}

function telepresence_theme() {
   $themes = array(
      'telepresence_template' => array(
          'template' => 'telepresence',
      ),
   );
   return($themes);
}