<?php

/*function nvf2_permission() {
	$perms = array();
	$perms['view nees media'] = array(
		'title' => 'View Nees Media',
		'description' => 'Allows someone to view the video feeds on the telepresence page');
	return $perms;
}*/

function nvf2_menu() {
	$items = array();
	$items['nvf2'] = array(
		'title' => 'Telepresence',
		'description' => 'Video feeds from NEES locations.',
		'page callback' => 'nvf2_page',
		'access arguments' => array('view nees media'),
		'type' => MENU_NORMAL_ITEM);
	return $items;
}

function nvf2_page() {
	$GoogleAPIKey = 'AIzaSyCPpIzXStBCfaojLIUMJupPBaAONdXU9LQ';
	drupal_add_js("https://maps.googleapis.com/maps/api/js?key=$GoogleAPIKey&sensor=true");
	drupal_add_library('system', 'ui.slider');
	drupal_add_library('system', 'ui.tabs');
	drupal_add_css(drupal_get_path('module','nvf2') . '/css/nvf2.css');
	drupal_add_css(drupal_get_path('module','nvf2') . '/js/libs/jQuery UI/css/ui-darkness/jquery-ui-1.10.0.custom.min.css');
	drupal_add_js(drupal_get_path('module','nvf2') . '/js/libs/handlebars-min.js');
	drupal_add_js(drupal_get_path('module','nvf2') . '/js/libs/underscore-min.js');
	drupal_add_js(drupal_get_path('module','nvf2') . '/js/libs/backbone-min.js');
	drupal_add_js(drupal_get_path('module','nvf2') . '/js/Model.js');
	drupal_add_js(drupal_get_path('module','nvf2') . '/js/View.js');
	drupal_add_js(drupal_get_path('module','nvf2') . '/js/Controller.js');
	drupal_add_js(drupal_get_path('module','nvf2') . '/js/App.js');

	$page = theme('nvf2_template');
	
	return $page;
}

function nvf2_theme() {
   $themes = array(
      'nvf2_template' => array(
          'template' => 'nvf2',
      ),
   );
   return($themes);
}
function nvf2_js_alter(&$js) {
	if($_GET['q'] == 'nvf2') {
		$js['misc/jquery.js']['data'] = 'http://code.jquery.com/jquery-1.8.3.js';
		$js['misc/ui/jquery.ui.core.min.js']['data'] = drupal_get_path('module','nvf2') . '/js/libs/jQuery UI/jquery-ui-1.10.0.custom.min.js';
	}
}
