<?php

function telepresence_permission() {
	$perms = array();
	$perms['access telepresence'] = array(
		'title' => 'Access Telepresence Portal',
		'description' => 'Allows user to view video feeds on the telepresence page.');
	$perms['administer telepresence'] = array(
		'title' => 'Administer Telepresence Portal Configuration',
		'description' => 'Change settings and content related to the telepresence module.');
	return $perms;
}

function telepresence_menu() {
	$items = array();
	$items['telepresence'] = array(
		'title' => t('Telepresence'),
		'description' => t('Video feeds from NEES locations.'),
		'page callback' => 'telepresence_page',
		'access arguments' => array('access telepresence'),
		'type' => MENU_NORMAL_ITEM
	);
	$items['admin/config/telepresence'] = array(
		'title' => 'Telepresence Configuration',
		'description' => t('Configuration options for the Telepresence application'),
		'page callback' => t('drupal_get_form'),
		'page arguments' => array('telepresence_config'),
		'access arguments' => array('administer telepresence'),
		'type' => MENU_NORMAL_ITEM
	);
	return $items;
}

function telepresence_config() {
	$form = array();

	$form['telepresence_about'] = array(
		'#title' => t('About'),
		'#type' => 'text_format',
		'#default_value' => telepresence_get_settings()
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => 'save',
		'#submit' => array('telepresence_save_settings')
	);
	return($form);
}

function telepresence_save_settings($form, &$form_state) {
	try {
		db_truncate('telepresence')->execute();

		db_insert('telepresence')
		->fields(array(
			'about' => $form_state['input']['telepresence_about']['value'])
		)
		->execute();
	} catch (Exception $e) {
		dsm($e);
	}
}

function telepresence_get_settings() {
	$r = db_select('telepresence', 't')
		->fields('t')
		->execute()
		->fetchAssoc();
	return $r['about'];
}

function telepresence_page() {
	$about       = telepresence_get_settings();
	$module_path = drupal_get_path('module', 'telepresence');

	drupal_add_css($module_path . '/css/font-awesome/css/font-awesome.min.css');
	drupal_add_css($module_path . '/css/kendo.common.min.css');
	drupal_add_css($module_path . '/css/kendo.black.min.css');

	drupal_add_js(
		array(
			'modulePath'         => $module_path,
			'telepresence_about' => $about
		),
		'setting'
	);

	drupal_add_css($module_path . '/css/telepresence.css');

	$page = theme('telepresence_template', array('module_path' => $module_path));
	
	return $page;
}

function telepresence_theme() {
   $themes = array(
      'telepresence_template' => array(
          'template' => 'telepresence',
      ),
   );
   return($themes);
}
